name: C/C++ CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: make 
      run: sudo apt-get install libgtest-dev
           sudo apt-get install cmake # install cmake
           cd /usr/src/gtest
           sudo cmake CMakeLists.txt
           sudo make
